/**
 * @author Mario Everardo Macias
 */
package com.TeamNumberOne.canbusbackend.Controller;

import com.TeamNumberOne.canbusbackend.Model.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

/**
 * Creates a controller for the Configuration model, this allows the population of data in the model,
 * and allows the model to be modified without full access to the model for the end user.
 * */
@CrossOrigin
@Controller // This means that this class is a com.TeamNumberOne.canbusbackend.Controller
@RequestMapping(path = "/Configuration")
public class ConfigurationManager {
    @Autowired
    // This means to get the bean called projectRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private Configuration config;

    @GetMapping(path = "/addConfig")
    public @ResponseBody String addcConfig(
            @RequestParam String analystInitials,
            @RequestParam String canConectorID,
            @RequestParam String vehicleID,
            @RequestParam String baudRate,
            @RequestParam String eventName,
            @RequestParam String eventDate,
            @RequestParam String DBCFileName
    ){
        config.setAnalystInitials(analystInitials);
        config.setCanConnectorID(canConectorID);
        config.setVehicleID(vehicleID);
        config.setBaudRate(baudRate);
        config.setEvent_name(eventName);
        config.setEvent_date(eventDate);
        config.setDBC_FILE_NAME(DBCFileName);
        return "Project Configuration has been set!";
    }

}
